aws:
    version: latest
    region: local-1
#    profile: "%env(DEMO_PROFILE)%"
    credentials:
        key: "%env(AWS_KEY)%"
        secret: "%env(AWS_SECRET)%"
    S3:
        version: '2006-03-01'
        endpoint: http://localstack:4566
    Sns:
        endpoint: http://localstack:4566
    Sqs:
        endpoint: http://localstack:4566
